### ISSUE TITLE
Add testing harness

### ISSUE THREAD

**Issue by javajawa** [mewbotorg/mewbot#11]
In order to have high quality code, we should start unit and integration testing.

 - [x] Select a python testing system and coverage library
 - [x] Create a place for tests to live
 - [x] Set it up to have similar linting as the main sources
 - [x] Set up a test system which supports coverage reporting
 - [x] Integrate it with a `tools/test.sh` and the github actions

**Comment by exachixkitsune** [comment]
What flavour of coverage are you looking for?

**Comment by javajawa** [comment]
Probably statement based rather than line based?

**Comment by exachixkitsune** [comment]
Had a look at pytest and pytest-cov, and I have a MWE; though I need to work out how to run a test that loads a file in...
or a way of doing that omitting the file...

(Further work is looking at something that isn't pytest)

**Comment by exachixkitsune** [comment]
So, pytest and pytest-cov gives us:

- relatively standard testing framework
- Easy integration of the coverage tool (pytest-cov also using the default coverage package, and the current settings we have in `pyproject.toml`.
- Output of pytest-cov into html, xml, or plaintext/annotated source (the html one is nice and useful)
- pytest-cov lists what's missing (line no for line coverage at least)

Downside; it looks like it's merging the statement coverage and branch coverage stats together and the threshold is both combined; and it's an overall percentage.
 I also cannot seem to make it fail if any file is untested.

I don't know how this would integrate into a github action, but I can create it to output stuff and it will hopefully operate properly.

If that's all ok, I will proceed.

**Comment by javajawa** [comment]
That all seems fine.

For the workflow/actions side, you can crib from the same source as I got the rest of the workflow stuff:
https://github.com/javajawa/py-tiny-orm/blob/2ce10aa/.github/workflows/lint.yml#L95-L172. That runs the tests against version python versions on two operating systems, and then combines the coverage reports.

**Comment by exachixkitsune** [comment]
Things to do

- [x] Create initial suite of unit tests
- [x] Create initial suite of functional tests
- [x] Connect into Github Actions/Workflow
