### ISSUE TITLE
Split codebase into packages

### ISSUE THREAD

**Issue by javajawa** [mewbotorg/mewbot#13]
Currently our setup logic is aiming to ship one `mewbot` package.
As we are aiming for a modular system with lots of extensibility, a monolith package is suboptimal.

Current suggestion:
  - `mewbot-core` contains the base packages `mewbot.core`
  - `mewbot-api` contains the `mewbot.component` and `mewbot.api` packages, and depend on `mewbot-core`. This is the package that will be a dependency of any "third party" modules
  - `mewbot-ui` will contain the GUI website. For now I think this will just contain the YAML loader
  - `mewbot` contains the bot runner itself, and depends on everything else. This will be the package people install when they want to run a bot

**Comment by ajCameron** [comment]
Trivial comment, but mewbot-console - modelled after the discord.py console - might also be handy. Will have a look over that package and see what inspiration can be taken.

**Comment by ajCameron** [comment]
(Additional thought - a convenience, composite package - possible called "mewbot-all" or something. Which just grabs everything.

Will this, normally, be a good idea? No. Not really. But it will be useful for testing - in particular interaction testing to make sure all components work well together).

**Comment by javajawa** [comment]
The "all" concept might be pretty easy if we work out how to do this with the `boto3[s3,ec2]` style packing tricks -- mewbot would be everything, and mewbot[runner,loader] would just be two bits
