### ISSUE TITLE
Pylint version not functional on windows

### ISSUE THREAD

**Issue by javajawa** [mewbotorg/mewbot#27]
> > it's erroring on pylint with a RecursionError; around colorama and asteroid

> Are those being pulled in by mewbot, or coming in from the global environment?

Good question.
So it appears that they are used by pylint / multiprocessing - pylint is spawning multiple processes, and so it's using multiprocessing, and that's failing because these are dependants...
I updated pylint and it failed.
Seems like, from looking at other github things, it's an issue with pylint and colorama specifically.
(https://github.com/PyCQA/pylint/issues/6012;
I am using:
pylint 2.13.5
dill 0.3.4 (in the traceback)
colorama 0.4.4)

__Originally posted by @exachixkitsune in https://github.com/mewler/mewbot/issues/22#issuecomment-1094336549__

**Comment by exachixkitsune** [comment]
For clarity, I am running pylint in a powershell scrip that does:
```
$Modules = '.\src .\examples'
Start-Process pylint -ArgumentList $Modules -Wait
```

it *is* reparable by adding "-j 1" into the pylint arguments (as below), but this is unlikely to be sustainable, and may want fixing later.

```
Start-Process pylint -ArgumentList @("-j 1",$Modules) -NoNewWindow -Wait
```

**Comment by javajawa** [comment]
I think I at least know why it is running in multi job mode:
https://github.com/mewler/mewbot/blob/032a57814a98a3b53e252fcf7924efc45df839ec/pyproject.toml#L9-L14

**Comment by exachixkitsune** [comment]
Can confirm, if I change this to `jobs=1` lints runs again.
I will confirm (today?) But that doesn't feel like an unreasonable change
